name: ShiftAndF
version: '${project.version}'
softdepend: [ PlaceholderAPI ]
main: cn.sandtripper.minecraft.shiftandf.ShiftAndF
api-version: '1.12'
authors: [ '沙酱紫漏' ]
description: Shift+F bind commands
commands:
  ShiftAndF:
    description: '/saf on|off|reload'
    usage: '/saf on|off|reload'
    aliases: [ saf ]
    permission: shiftandf.command
    permission-message: You don't have permission to perform this command.